export const SELECT_RECIPE = 'SELECT_RECIPE';
export const ADD_RECIPE = 'ADD_RECIPE';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const UPDATE_RECIPE_LIST = 'UPDATE_RECIPE_LIST';
export const LOAD_STATE = 'LOAD_STATE';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const CHANGE_POPUP_STATUS = 'CHANGE_POPUP_STATUS';
